#!/bin/bash

function usage_main() {
  printf "Usage:\n"
  printf "\tetrade {-h --help}\n"
  local cmd_len=11
  printf "\tetrade %-${cmd_len}s {-h --help}\n"                            "<command>"
  printf "\tetrade %-${cmd_len}s <subcommand>\n"                           "auth"
  printf "\tetrade %-${cmd_len}s [subcommand] [options] <ticker symbol>\n" "quote"
  printf "\tetrade %-${cmd_len}s <subcommand> [options]\n"                 "calc"
}

function help_main() {
  printf "Etrade CLI - "
  printf "Command Line Interface to access Etrade using developer keys for a personal account"
  printf "\n\n"
  usage_main
}

export PARENT_PATH=$(cd "$(dirname "$0")"; pwd)

source "$PARENT_PATH/lib/common/settings.sh"
source "$PARENT_PATH/lib/common/http_defns.sh"
source "$PARENT_PATH/lib/common/validation.sh"
source "$PARENT_PATH/lib/auth/auth.sh"
source "$PARENT_PATH/lib/quote/quote.sh"
source "$PARENT_PATH/lib/calc/calc.sh"

load_persistent_values

if [ ! -d "${CACHE_DIR}" ]; then
  mkdir -p "${CACHE_DIR}"
fi

case $1 in
  auth)
    shift
    execute_auth "$@"
    ;;
  quote)
    shift
    execute_quote "$@"
    ;;
  calc)
    shift
    execute_calc "$@"
    ;;
  -h|--help)
    help_main
    ;;
  *)
    printf "Error: Unrecognized command '$1'\n\n" 1>&2
    usage_main 1>&2
    exit 1
    ;;
esac
