#!/bin/bash

export PARENT_PATH=$(cd "$(dirname "$0")"; pwd)

source "$PARENT_PATH/lib/common/file_defns.sh"
source "$PARENT_PATH/lib/common/http_defns.sh"
source "$PARENT_PATH/lib/common/input.sh"
source "$PARENT_PATH/lib/common/key_defns.sh"
source "$PARENT_PATH/lib/common/validation.sh"
source "$PARENT_PATH/lib/auth/auth.sh"
source "$PARENT_PATH/lib/quote/quote.sh"
source "$PARENT_PATH/lib/calc/calc.sh"

load_persistent_values

if [ ! -d "${QUOTE_DIR}" ]; then
  mkdir -p "${QUOTE_DIR}"
fi

case $1 in
  auth)
    shift
    execute_auth $@
    ;;
  quote)
    shift
    execute_quote $@
    ;;
  calc)
    shift
    execute_calc $@
    ;;
  *)
    echo "Error"
    exit 1
    ;;
esac
